version: '3'
services:
  inventory-db:
    image: postgres:14
    container_name: inventory-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=senhasegura
      - POSTGRES_DB=inventory
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    # env_file:
    #  - ./.env